{{- if .Values.openid.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sky-budget.fullname" . }}-openid
  labels:
    {{- include "sky-budget.labels" . | nindent 4 }}
type: Opaque
stringData:
  client-secret: {{ .Values.openid.clientSecret | quote }}
{{- end }}
